apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-vm-1
  annotations:
    kubernetes.io/target-runtime: virtlet
    VirtletVolumes: >
      [
        {
          "Name": "docker",
          "Format": "qcow2",
          "Capacity": "2048",
          "CapacityUnit": "MB"
        }
      ]
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: extraRuntime
            operator: In
            values:
            - virtlet
  containers:
  - name: ubuntu-vm-1
    image: virtlet/cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
  volumes:
  - name: test
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: nocloud
        metadata: |
          instance-id: ubuntu-vm-1-001
          local-hostname: ubuntu-vm-1
        userdata: |
          #cloud-config
          mounts:
          - [ /dev/vdc1, /var/lib/docker ]
          write_files:
          - path: /etc/systemd/system/docker.service.d/env.conf
            permissions: "0644"
            owner: root
            content: |
              [Service]
              Environment="DOCKER_OPTS=--storage-driver=overlay"
          - path: /etc/apt/sources.list.d/kubernetes.list
            permissions: "0644"
            owner: root
            content: |
              deb http://apt.kubernetes.io/ kubernetes-xenial main
          users:
          - name: root
            ssh-authorized-keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJEcFDXEK2ZbX0ZLS1EIYFZRbDAcRfuVjpstSc0De8+sV1aiu+dePxdkuDRwqFtCyk6dEZkssjOkBXtri00MECLkir6FcH3kKOJtbJ6vy3uaJc9w1ERo+wyl6SkAh/+JTJkp7QRXj8oylW5E20LsbnA/dIwWzAF51PPwF7A7FtNg9DnwPqMkxFo1Th/buOMKbP5ZA1mmNNtmzbMpMfJATvVyiv3ccsSJKOiyQr6UG+j7sc/7jMVz5Xk34Vd0l8GwcB0334MchHckmqDB142h/NCWTr8oLakDNvkfC1YneAfAO41hDkUbxPtVBG5M/o7P4fxoqiHEX+ZLfRxDtHB53 me@localhost
          ssh_pwauth: True
          runcmd:
          - [ apt-get, update ]
          - [ apt-get, install, -y, --force-yes, apt-transport-https ]
          - [ /bin/sh, -c, "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -" ]

          - [ apt-get, update ]
          - [ apt-get, install, -y, --force-yes, docker.io ]
          - [ apt-get, install, -y, --force-yes, kubelet, kubeadm, kubectl, kubernetes-cni ]
          - [ sed, -i, "s/--authorization-mode=Webhook //", "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf" ]
          - [ systemctl, daemon-reload ]
